# Generated by Django 6.0.1 on 2026-02-04 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_alert_options_alter_device_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('danger', 'Danger Zone'), ('harassment', 'Harassment'), ('theft', 'Theft/Crime'), ('accident', 'Accident'), ('fire', 'Fire'), ('medical', 'Medical Emergency'), ('suspicious', 'Suspicious Activity'), ('other', 'Other')], max_length=20)),
                ('message', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_km', models.FloatField(default=1.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('reports_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['latitude', 'longitude', 'is_active'], name='accounts_co_latitud_176245_idx')],
            },
        ),
    ]
