# Generated by Django 6.0.1 on 2026-02-04 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_communityalert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyCompanion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('check_in_interval_minutes', models.IntegerField(default=5)),
                ('deviation_threshold_km', models.FloatField(default=0.5)),
                ('notification_enabled', models.BooleanField(default=True)),
                ('last_location_latitude', models.FloatField(blank=True, null=True)),
                ('last_location_longitude', models.FloatField(blank=True, null=True)),
                ('last_location_update', models.DateTimeField(blank=True, null=True)),
                ('last_check_in', models.DateTimeField(blank=True, null=True)),
                ('companion_acknowledged', models.BooleanField(default=False)),
                ('deviation_alert_sent', models.BooleanField(default=False)),
                ('inactivity_alert_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='safety_companion_for', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_companion_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
