# Generated by Django 6.0.1 on 2026-02-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_safetycompanion'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsqueue',
            name='attempt_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='smsqueue',
            name='last_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='smsqueue',
            name='max_attempts',
            field=models.IntegerField(default=5),
        ),
    ]
