# Generated by Django 6.0.1 on 2026-02-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_smsqueue_attempt_count_smsqueue_last_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100)),
                ('date', models.DateField()),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('key', 'date')},
            },
        ),
    ]
